name: Run pytest and Merge to Prod

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11  # Choose your Python version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        run: pytest

      - name: Merge to Prod (if tests pass)
        if: success()
        run: |
          git checkout prod
          git merge dev
          git push origin prod
