---
name: Run pytest and Merge to Prod
on:
  push:
    branches:
      - developer
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set u
      - name: Install dependencies
        run: pip install -r requirements.txt
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Run pytest
        run: pytest
      - name: Merge to Prod (if tests pass)
        if: success(
        run: |
          git checkout prod
          git merge developer
          git push origin prod
