# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - PyMaggie

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      FLASK_APP: ${{ secrets.FLASK_APP }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://pymaggie.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_8380c4395cab4f0ab6aaf2a50496f236 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4257ac4c3a8f4ed58cb61d7be4744895 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:      
        push: true
        tags: pymaggie.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8380c4395cab4f0ab6aaf2a50496f236 }}/pymaggie-container:${{ github.sha }}
        build-args: SECRET_KEY= ${{ env.SECRET_KEY }},DATABASE_URL= ${{ env.DATABASE_URL }},FLASK_APP= ${{ env.FLASK_APP }}
        file: ./Dockerfile
        

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'PyMaggie'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ce07cfe7fa6c4778890541dc7bb53cf6 }}
        images: 'pymaggie.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_8380c4395cab4f0ab6aaf2a50496f236 }}/pymaggie-container:${{ github.sha }}'     
        
